#!/usr/bin/env bash
# Auto-generated pre-compaction snapshot. Fires on the PreCompact hook (manual or auto)
# so a handoff.md always exists at the project root right before context is summarized.
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/../.." || exit 0

{
  echo "# Handoff snapshot (auto-generated)"
  echo
  echo "_Generated by PreCompact hook: $(date '+%Y-%m-%d %H:%M:%S %Z')_"
  echo
  echo "This is a deterministic git-state snapshot, not a narrative summary. If the assistant"
  echo "already wrote a fuller handoff.md this session, that content may be overwritten below —"
  echo "check chat history for the narrative version if this snapshot alone isn't enough context."
  echo
  echo "## Git status"
  echo '```'
  git status --short 2>/dev/null || echo "(not a git repo or git unavailable)"
  echo '```'
  echo
  echo "## Uncommitted diff (stat)"
  echo '```'
  git diff --stat 2>/dev/null
  echo '```'
  echo
  echo "## Recent commits"
  echo '```'
  git log --oneline -10 2>/dev/null || echo "(no commits yet)"
  echo '```'
  echo
  echo "## Current branch"
  echo '```'
  git branch --show-current 2>/dev/null
  echo '```'
} > handoff.md

exit 0
